MyImdb/Entities/Movie.cs
using MyImdb.Business;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyImdb.Entities {
	public class Movie {
		public Guid Id { get; set; }
		public int Rank { get; set; }

		[MaxLength(100)]
		[Required]
		public string Title { get; set; } = string.Empty;
		public int Year { get; set; }

		[MaxLength(200)]
		public string Storyline { get; set; } = String.Empty;
		public DateTime CreationDateUtc { get; set; }

		public Guid GenreId { get; set; }
		public Genre Genre { get; set; } = new();

		public List<MovieActor> MovieActors { get; } = new();

		[NotMapped]
		public DateTimeOffset CreationDate {
			get {
				return new DateTimeOffset(CreationDateUtc, TimeSpan.Zero);
			}
			set {
				CreationDateUtc = value.UtcDateTime;
			}
		}
	}
}

MyImdb/Models/Movie.cs
namespace MyImdb.Models {
    
}

MyImdb/Controllers/MovieController.cs
using Api.Genres;
using Api.Movies;
using Microsoft.AspNetCore.Mvc;
using MyImdb.Business;
using MyImdb.Business.Repositories;
using MyImdb.Business.Services;
using MyImdb.Entities;
using MyImdb.Services;
using MyImdb.ViewModels;
using System.Diagnostics.CodeAnalysis;

namespace MyImdb.Controllers {
	[ApiController]
	[Route("api/movies")]
	public class MovieController : Controller {
		private readonly MovieRepository movieRepository;
		private readonly MovieService movieService;
		private readonly GenreRepository genreRepository;
		private readonly ExceptionBuilder exceptionBuilder;
		private readonly ModelConverter mc;

		public MovieController(
			MovieRepository movieRepository,
			MovieService movieService,
			GenreRepository genreRepository,
			ExceptionBuilder exceptionBuilder,
			ModelConverter mc
		) {
			this.movieRepository = movieRepository;
			this.movieService = movieService;
			this.genreRepository = genreRepository;
			this.exceptionBuilder = exceptionBuilder;
			this.mc = mc;
		}

		// GET: /api/movies/
		// List all movies
		[HttpGet]
		public async Task<List<MovieModel>> List(int n = 20) {
			// TODO: pagination API, name filter

			var movies = await movieRepository.SelectTopNAsync(n);

			return movies.ConvertAll(m => mc.ToModel(m));
		}

		// GET: /api/movies/
		// Create a movie
		[HttpPost]
		public async Task<MovieModel> Create(MovieData request) {

			var movie = await movieService.CreateAsync(request.Rank, request.Title, request.Year, request.Storyline, request.Genre);

			return mc.ToModel(movie);
		}

		// GET: /api/movies/{id}
		// List movie by id
		[HttpGet("{id}")]
		public async Task<MovieModel> Get(Guid id) {
			var movie = await movieRepository.SelectByIdAsync(id);

			return mc.ToModel(movie!);
		}

		// PUT: /api/movies/{id}
		// Update a movie by id
		[HttpPut("{id}")]
		public async Task<MovieModel> Update(Guid id, MovieData request) {
			var movie = await movieRepository.SelectByIdAsync(id);

			if (movie == null) {
				throw exceptionBuilder.Api(Api.ErrorCodes.MovieNotFound, new { id });
			}

			await movieService.UpdateAsync(movie, request.Title);

			return mc.ToModel(movie);
		}

		// DELETE: /api/genres/{id}
		// Delete a genre by id
		[HttpDelete("{id}")]
		public async Task Delete(Guid id) {
			var movie = await movieRepository.SelectByIdAsync(id);

			if (movie == null) {
				throw exceptionBuilder.Api(Api.ErrorCodes.MovieNotFound, new { id });
			}

			await movieService.DeleteAsync(movie);
		}
	}
}

MyImdb/Views/Movie/Create.cshtml
@model MyImdb.ViewModels.MovieCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Add Movie</h2>
<div>
    Please fill the movie data to add a new movie:
</div>
<br />
<div class="container">
    <form asp-action="Create">
        <div class="mb-3 row">
            <label asp-for="Title" class="col-sm-1 col-form-label"><b>Title</b></label>
            <div class="col-sm-8">
                <input asp-for="Title" class="form-control">
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <label asp-for="Rank" class="col-sm-1 col-form-label"><b>Rank</b></label>
            <div class="col-sm-2">
                <input asp-for="Rank" class="form-control">
                <span asp-validation-for="Rank" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <label asp-for="Year" class="col-sm-1 col-form-label"><b>Year</b></label>
            <div class="col-sm-2">
                <input asp-for="Year" class="form-control">
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <label asp-for="StoryLine" class="col-sm-1 col-form-label"><b>StoryLine</b></label>
            <div class="col-sm-8">
                <textarea asp-for="StoryLine" type="textarea" class="form-control" rows="4"></textarea>
                <span asp-validation-for="StoryLine" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-check" viewBox="0 0 16 16">
                        <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z" />
                    </svg>
                    save
                </button>
            </div>
        </div>

    </form>
</div>

<div style="margin-top: 3rem;">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left"
         viewBox="0 0 16 16">
        <path fill-rule="evenodd"
              d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z" />
    </svg>
    <a asp-action="Index">Back to Movies</a>
</div>

MyImdb/Views/Movie/Index.cshtml
@using MyImdb.ViewModels
@model List<MovieListViewModel>
@{
    ViewData["Title"] = "Index";
}

@*@if (ViewBag.Message is not null)
    {
    <div class="alert alert-info">
    <p>@ViewBag.Message</p>
    </div>
    }
*@

@if (ViewData["Message"] is not null)
{
    <div class="alert alert-info">
        <p>@ViewData["Message"]</p>
    </div>
}

<h1>Movies</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Rank</th>
            <th scope="col">Year</th>
        </tr>
    </thead>
    <tbody>
        @if (Model is not null)
        {
            foreach (var movie in Model)
            {
                <tr>
                    <td>@movie.Title</td>
                    <td>@movie.Rank</td>
                    <td>@movie.Year</td>
                </tr>
            }
        }
    </tbody>
</table>

<button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Create", "Movie")'">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle"
         viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"></path>
        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z">
        </path>
    </svg>
    Add movie
</button>

<div style="margin-top: 2rem;">
    Click <a asp-action="MovieOfTheMonth">here</a> to check out the movie of the month.
</div>

MyImdb/Views/Movie/MovieListActors.cshtml
@{

}

<h1>Actors</h1>

MyImdb/Views/Movie/MovieListGenres.cshtml
@{
}

<h1>Genres</h1>

MyImdb/Views/Movie/MovieOfTheMonth.cshtml
@using MyImdb.ViewModels
@model MovieOfTheMonthListViewModel
@{

}

<div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
        <div class="col-md-4">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg"
                 role="img" preserveAspectRatio="xMidYMid slice" focusable="false">
                <rect width="100%" height="100%" fill="#868e96"></rect>
                <image href="https://img.icons8.com/pastel-glyph/2x/movie-beginning.png" height="100%" width="100%" />
            </svg>
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h4 class="card-title">@Model?.Title</h4>
                <h6>Rank: @Model?.Rank</h6>
                <h6>Director: @Model?.Director</h6>
                <p class="card-text">@Model?.StoryLine</p>
                <a href="#" class="btn btn-primary">Watch Trailer</a>
                <a href="#" class="btn btn-primary">Add to Watchlist</a>
            </div>
        </div>
    </div>
</div>

<div style="margin-top: 3rem;">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left"
         viewBox="0 0 16 16">
        <path fill-rule="evenodd"
              d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z" />
    </svg>
    <a asp-controller="Movie" asp-action="Index">Back to Movies</a>
</div>